/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SsFreedomAdminWidget {
        "canPublish": boolean;
        "cmsEditLink": string;
        "isPublished": boolean;
        "pageClassName": string;
        "pageId": number;
        "refreshPublishedStatus": () => Promise<void>;
        "stage": "Stage" | "Live";
    }
    interface SsFreedomObjectAlertButton {
        "element": HTMLElement;
    }
    interface SsFreedomObjectOptionsButton {
        "element": HTMLElement;
    }
    interface SsFreedomObjectOptionsPanel {
        "element": HTMLElement;
    }
}
declare global {
    interface HTMLSsFreedomAdminWidgetElement extends Components.SsFreedomAdminWidget, HTMLStencilElement {
    }
    var HTMLSsFreedomAdminWidgetElement: {
        prototype: HTMLSsFreedomAdminWidgetElement;
        new (): HTMLSsFreedomAdminWidgetElement;
    };
    interface HTMLSsFreedomObjectAlertButtonElement extends Components.SsFreedomObjectAlertButton, HTMLStencilElement {
    }
    var HTMLSsFreedomObjectAlertButtonElement: {
        prototype: HTMLSsFreedomObjectAlertButtonElement;
        new (): HTMLSsFreedomObjectAlertButtonElement;
    };
    interface HTMLSsFreedomObjectOptionsButtonElement extends Components.SsFreedomObjectOptionsButton, HTMLStencilElement {
    }
    var HTMLSsFreedomObjectOptionsButtonElement: {
        prototype: HTMLSsFreedomObjectOptionsButtonElement;
        new (): HTMLSsFreedomObjectOptionsButtonElement;
    };
    interface HTMLSsFreedomObjectOptionsPanelElement extends Components.SsFreedomObjectOptionsPanel, HTMLStencilElement {
    }
    var HTMLSsFreedomObjectOptionsPanelElement: {
        prototype: HTMLSsFreedomObjectOptionsPanelElement;
        new (): HTMLSsFreedomObjectOptionsPanelElement;
    };
    interface HTMLElementTagNameMap {
        "ss-freedom-admin-widget": HTMLSsFreedomAdminWidgetElement;
        "ss-freedom-object-alert-button": HTMLSsFreedomObjectAlertButtonElement;
        "ss-freedom-object-options-button": HTMLSsFreedomObjectOptionsButtonElement;
        "ss-freedom-object-options-panel": HTMLSsFreedomObjectOptionsPanelElement;
    }
}
declare namespace LocalJSX {
    interface SsFreedomAdminWidget {
        "canPublish"?: boolean;
        "cmsEditLink"?: string;
        "isPublished"?: boolean;
        "pageClassName"?: string;
        "pageId"?: number;
        "stage"?: "Stage" | "Live";
    }
    interface SsFreedomObjectAlertButton {
        "element": HTMLElement;
    }
    interface SsFreedomObjectOptionsButton {
        "element": HTMLElement;
    }
    interface SsFreedomObjectOptionsPanel {
        "element": HTMLElement;
    }
    interface IntrinsicElements {
        "ss-freedom-admin-widget": SsFreedomAdminWidget;
        "ss-freedom-object-alert-button": SsFreedomObjectAlertButton;
        "ss-freedom-object-options-button": SsFreedomObjectOptionsButton;
        "ss-freedom-object-options-panel": SsFreedomObjectOptionsPanel;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ss-freedom-admin-widget": LocalJSX.SsFreedomAdminWidget & JSXBase.HTMLAttributes<HTMLSsFreedomAdminWidgetElement>;
            "ss-freedom-object-alert-button": LocalJSX.SsFreedomObjectAlertButton & JSXBase.HTMLAttributes<HTMLSsFreedomObjectAlertButtonElement>;
            "ss-freedom-object-options-button": LocalJSX.SsFreedomObjectOptionsButton & JSXBase.HTMLAttributes<HTMLSsFreedomObjectOptionsButtonElement>;
            "ss-freedom-object-options-panel": LocalJSX.SsFreedomObjectOptionsPanel & JSXBase.HTMLAttributes<HTMLSsFreedomObjectOptionsPanelElement>;
        }
    }
}
