/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface SsFreedomAdminWidget {}
  interface SsFreedomObjectOptionsButton {
    'objectClass': string;
    'objectId': string;
  }
  interface SsFreedomObjectOptionsPanel {
    'objectClass': string;
    'objectId': string;
  }
}

declare global {


  interface HTMLSsFreedomAdminWidgetElement extends Components.SsFreedomAdminWidget, HTMLStencilElement {}
  var HTMLSsFreedomAdminWidgetElement: {
    prototype: HTMLSsFreedomAdminWidgetElement;
    new (): HTMLSsFreedomAdminWidgetElement;
  };

  interface HTMLSsFreedomObjectOptionsButtonElement extends Components.SsFreedomObjectOptionsButton, HTMLStencilElement {}
  var HTMLSsFreedomObjectOptionsButtonElement: {
    prototype: HTMLSsFreedomObjectOptionsButtonElement;
    new (): HTMLSsFreedomObjectOptionsButtonElement;
  };

  interface HTMLSsFreedomObjectOptionsPanelElement extends Components.SsFreedomObjectOptionsPanel, HTMLStencilElement {}
  var HTMLSsFreedomObjectOptionsPanelElement: {
    prototype: HTMLSsFreedomObjectOptionsPanelElement;
    new (): HTMLSsFreedomObjectOptionsPanelElement;
  };
  interface HTMLElementTagNameMap {
    'ss-freedom-admin-widget': HTMLSsFreedomAdminWidgetElement;
    'ss-freedom-object-options-button': HTMLSsFreedomObjectOptionsButtonElement;
    'ss-freedom-object-options-panel': HTMLSsFreedomObjectOptionsPanelElement;
  }
}

declare namespace LocalJSX {
  interface SsFreedomAdminWidget extends JSXBase.HTMLAttributes<HTMLSsFreedomAdminWidgetElement> {}
  interface SsFreedomObjectOptionsButton extends JSXBase.HTMLAttributes<HTMLSsFreedomObjectOptionsButtonElement> {
    'objectClass': string;
    'objectId': string;
  }
  interface SsFreedomObjectOptionsPanel extends JSXBase.HTMLAttributes<HTMLSsFreedomObjectOptionsPanelElement> {
    'objectClass': string;
    'objectId': string;
  }

  interface IntrinsicElements {
    'ss-freedom-admin-widget': SsFreedomAdminWidget;
    'ss-freedom-object-options-button': SsFreedomObjectOptionsButton;
    'ss-freedom-object-options-panel': SsFreedomObjectOptionsPanel;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


